### ISSUE TITLE
Submission Checklist

### ISSUE THREAD

**Issue by jdlawton** [jdlawton/noteworthy#9]
- [ ] Application front end must connect to an Express.js back end.
- [ ] Application back end must store notes with unique IDs in a JSON file.
- [ ] Application must be deployed to Heroku.
- [ ] Application deployed at live URL.
- [ ] Application loads with no errors.
- [ ] Application console is free of errors.

Things to Submit:
- [ ] The URL of the functional, deployed application. (Heroku)
- [ ] The URL of the GitHub repository. Give the repository a unique name and include a README describing the project.
